export const COUNTRIES = [
  "Afeganistão", "África do Sul", "Albânia", "Alemanha", "Andorra", "Angola", 
  "Antígua e Barbuda", "Arábia Saudita", "Argélia", "Argentina", "Armênia", 
  "Austrália", "Áustria", "Azerbaijão", "Bahamas", "Bahrein", "Bangladesh", 
  "Barbados", "Bélgica", "Belize", "Benin", "Bielorrússia", "Bolívia", 
  "Bósnia e Herzegovina", "Botsuana", "Brasil", "Brunei", "Bulgária", 
  "Burkina Faso", "Burundi", "Butão", "Cabo Verde", "Camarões", "Camboja", 
  "Canadá", "Catar", "Cazaquistão", "Chade", "Chile", "China", "Chipre", 
  "Colômbia", "Comores", "Coreia do Norte", "Coreia do Sul", "Costa do Marfim", 
  "Costa Rica", "Croácia", "Cuba", "Dinamarca", "Djibouti", "Dominica", 
  "Egito", "El Salvador", "Emirados Árabes Unidos", "Equador", "Eritreia", 
  "Escócia", "Eslováquia", "Eslovênia", "Espanha", "Estados Unidos", "Estônia", 
  "Eswatini", "Etiópia", "Fiji", "Filipinas", "Finlândia", "França", "Gabão", 
  "Gâmbia", "Gana", "Geórgia", "Grécia", "Granada", "Guatemala", "Guiana", 
  "Guiné", "Guiné Equatorial", "Guiné-Bissau", "Haiti", "Honduras", "Hungria", 
  "Iêmen", "Índia", "Indonésia", "Inglaterra", "Irã", "Iraque", "Irlanda", 
  "Irlanda do Norte", "Islândia", "Israel", "Itália", "Jamaica", "Japão", 
  "Jordânia", "Kosovo", "Kuwait", "Laos", "Lesoto", "Letônia", "Líbano", 
  "Libéria", "Líbia", "Liechtenstein", "Lituânia", "Luxemburgo", "Macedônia do Norte", 
  "Madagascar", "Malásia", "Malawi", "Maldivas", "Mali", "Malta", "Marrocos", 
  "Maurício", "Mauritânia", "México", "Mianmar", "Moçambique", "Moldávia", 
  "Mônaco", "Mongólia", "Montenegro", "Namíbia", "Nepal", "Nicarágua", 
  "Níger", "Nigéria", "Noruega", "Nova Zelândia", "Omã", "País de Gales", 
  "Países Baixos", "Panamá", "Papua Nova Guiné", "Paquistão", "Paraguai", 
  "Peru", "Polônia", "Porto Rico", "Portugal", "Quênia", "Quirguistão", 
  "República Centro-Africana", "República Democrática do Congo", "República do Congo", 
  "República Dominicana", "República Tcheca", "Romênia", "Ruanda", "Rússia", 
  "Samoa", "San Marino", "São Tomé e Príncipe", "Senegal", "Sérvia", "Seychelles", 
  "Singapura", "Síria", "Somália", "Sri Lanka", "Sudão", "Sudão do Sul", "Suécia", 
  "Suíça", "Suriname", "Tailândia", "Taiwan", "Tajiquistão", "Tanzânia", "Timor-Leste", 
  "Togo", "Tonga", "Trinidad e Tobago", "Tunísia", "Turcomenistão", "Turquia", 
  "Ucrânia", "Uganda", "Uruguai", "Uzbequistão", "Vanuatu", "Vaticano", "Venezuela", 
  "Vietnã", "Zâmbia", "Zimbábue"
];
